# Generated by Django 5.1.5 on 2025-01-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movements',
            old_name='nombre',
            new_name='name',
        ),
    ]
