# Generated by Django 5.1.5 on 2025-01-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0002_rename_nombre_movements_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Nombre'),
        ),
    ]
