# Generated by Django 5.1.5 on 2025-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0007_movements_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('class_name', models.CharField(max_length=75)),
            ],
        ),
    ]
