# Generated by Django 5.1.5 on 2025-01-16 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75, verbose_name='Nombre')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('amount', models.FloatField(verbose_name='Monto')),
            ],
        ),
    ]
