# Generated by Django 5.1.5 on 2025-02-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0004_movements_type_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
        ),
    ]
