# Generated by Django 5.1.5 on 2025-02-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0006_user_is_active_user_is_admin_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='Gestor.user'),
            preserve_default=False,
        ),
    ]
