# Generated by Django 5.1.5 on 2025-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0008_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='type_movement',
            field=models.BooleanField(default=False),
        ),
    ]
